### ISSUE TITLE
Chapter 23 Ex15

### ISSUE THREAD

**Issue by Josh1603** [Chrinkus/stroustrup-ppp#20]
I came up with mathematical patterns such as factorials and fibonacci sequences for this one (which segues quite nicely into the postscript for that chapter...).

Whether or not those sorts of patterns can actually be expressed as regex is beyond me.

I did see a couple of blog posts, particularly from a guy under the name 'Polygenelubricants', which seemingly managed to express those sorts of patterns with regex. Even so, it really doesn't seem to be the most practical way to express them.

**Comment by Chrinkus** [comment]
This one still stumps me. I use a log of regex's in my tooling for work and have yet to come upon a pattern that can't be expressed. They DO get quite long and ugly sometimes but that wasn't the question.
