### ISSUE TITLE
Calculator.cpp example issue : Non-void function does not return a value in all control paths

### ISSUE THREAD

**Issue by acratophorux** [Chrinkus/stroustrup-ppp#25]
### non-void function does not return a value in all control paths
I was doing the calculator problem in chapter 8 (Exercise 1) when I ran into this problem. The problem is in the definition of the function `Token_stream::get()`. I used Xcode for this exercise. 
The error showed by Xcode is `Non-void function does not return a value in all control paths`. It does not provide anything else. From what I understand, there could be a scenario when the `get()` function won't go through any of the switch-cases which could cause problems. Although I haven't been able to find the solution to this problem.
I would appreciate if this issue is addressed.

**P.S.** I used the same code from the solutions in this project. So I am sure that there are no syntax errors.

**Comment by Chrinkus** [comment]
Thanks for pointing this out! When I did these exercises I was not very knowledgeable about compiler flags and the more rigorous error checking that could be employed. I assume that when XCode compiles C programs it adds some flags that warn about this behaviour and/or treat warnings as errors and refuse to compile.

That particular function has a `switch` with a default case. The default case has an elaborate `if` chain too. Every path through has a return statement so there is no way of reaching the end of the function. If control DOES reach the end there is the `error()` call. This is a function that is in the `std_lib_facilities.h` header that bootstraps us through the first part of the text. It's got a lot going on in it but the error function can be found at line 137. It takes a string and `throw`s the error, effectively unwinding the stack and exiting the function through a giant gaping hole in the wall.

In your own code you can add a `return Token{0};` at the end of the `get` function and that should convince XCode.

Let me know here if it works.

**Comment by acratophorux** [comment]
Yes, using `return Token{0};` does solve the problem for the time being and shuts off the Xcode error/warning; though I am not sure that returning `Token{0}` won’t interfere with and cause further problems when the output of `get()` is used in the program. But, again, as you said, there is no way of reaching the end of the function, so I guess it is sufficient for now.

---
Just to bring it to your notice, the same problem also lies in the `Symbol_table::get_value(string s)` function.

```
double Symbol_table::get_value(string s)    // return the value of the Variable names s
{
    for(const Variable& v : var_table)
        if(v.name == s) return v.value;
    error("get : undefined variable", s);
    //return 0;
} 
```

Here, returning any value other than `v.value` is a logical error which leaves us with no workaround.

To me, the problem seems to be attached with `error()` function as it does not return **the type of the value** to be supposedly returned by the function in which `error()` function is used.

**Comment by Chrinkus** [comment]
It's the same thing. If we get that far in the function we have an error. Rather than return an error value like in C we throw an error and rely on the caller to catch it. It's unfortunate that XCode doesn't detect the `throw`.
